cpf=""
interval=3600
url="http://corporativo.directlog.com.br/track_individual/index.asp?numtracking="
num_tracking=""
email_sender=''
email_smtp_port=465
email_smtp_user=''
email_smtp_host=''
email_smtp_password=""
email_receivers=""